### ISSUE TITLE
Start date and end date fields in upcoming events

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitjsite-backend#21]
Create two fields for dates in this model. 
It needs to be shown in the home page

**Comment by princeverma-ai** [comment]
done

**Comment by harimurugan1989** [comment]
Remove the time field.. you have date and time field instead of date field.

We need only the starting date of the event

**Comment by Adityagupta1625** [comment]
we cannot exclude time because by default it needs time also along with date to save in mongo db
