### ISSUE TITLE
Create another newpage route. 

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitjsite-backend#29]
In order to avoid multiple control and have all other control like logs, created and updated time. 

Create a new model with following fields 

1) Title1 ( it will be shown below navbar above institute image)
2) Title2 (it will be shown in the body of the html page)
3) Description ( where we simply paste the source code from ckeditor)
4) show 
5) new 
6)order 
7)newpage 
8)pdf link 

All other common fields as well. 

We will use the old new route to store the html page design and we won't use it anywhere in front end. 

Design will be done in ckeditor and source code will be copied and pasted in description field. 

Currently tailwind is overriding the css. If we can some how stop it. This page problem is resolved. 

This route we will use similar to template page with small changes (if needed we create new page with template). 

Old route is also required to see the design which is not possible with adminbro. 

For sections like student corner, notices, tender, notices.. They have to do the copy paste in the existing description field. 

/n /t we don't need to bother if we are copy pasting source code. 

It solves all our issues hopefully.

**Comment by Adityagupta1625** [comment]
done
