### ISSUE TITLE
Timestamps in AdminBro

### ISSUE THREAD

**Issue by dohitdeegwal** [wdmc-nitj/nitjsite-backend#74]
All the forms in AdminBro have the createdAt and updatedAt fields, which has two drawbacks:
1. The updatedAt field doesn't get updated automatically when data is edited
2. The timestamp in these fields can be edited using the form

**Comment by harimurugan1989** [comment]
Time will be updated correctly once we move our server to internal.. Currently it is showing Western time 

Even though it shows option to edit the date and time. It won't get saved.
